version: "3.9"

services:
  back:
    image: transcribing_web_back:latest
    container_name: osa_tr_back
    env_file:
      - back/.env.prod
    restart: always
    depends_on:
      - server
  front:
    image: transcribing_web_front:latest
    container_name: osa_tr_front
    env_file:
      - front/.env.prod
    ports:
      - "5173:5173"
  server:
    image: transcribing_web_server:latest
    container_name: osa_tr_server
    restart: always
    env_file:
      - server/.env.prod
    depends_on:
      - ru_model
      - ua_model
  ru_model:
    image: alphacep/kaldi-en:latest
    container_name: osa_tr_ru_model
    volumes:
      - ./models/russian:/opt/vosk-model-en/model
  ua_model:
    image: alphacep/kaldi-en:latest
    container_name: osa_tr_ua_model
    volumes:
      - ./models/ukrainan:/opt/vosk-model-en/model







